load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library", "kt_jvm_test")

#kt_jvm_test(
#    name = "tests",
#    srcs = glob(["*.kt"]),
#    test_class = "me.williamhester.kdash.web.CreateUserTest",
#    associates = [
#        "//main/java/me/williamhester/kdash/web",
#    ],
#    deps = [
#        "@maven//:com_google_flogger_flogger",
#        "@maven//:com_google_protobuf_protobuf_java_util",
#        "@maven//:com_google_truth_truth",
#        "@maven//:io_javalin_javalin",
#        "@maven//:org_mindrot_jbcrypt",
#        "@maven//:junit_junit",
#        "@kdash//main/java/me/williamhester/kdash/api",
#        "//main/proto:telemetry_java_proto",
#    ],
#)