load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Kotlin
rules_kotlin_version = "1.8"
rules_kotlin_sha = "01293740a16e474669aba5b5a1fe3d368de5832442f164e4fbfc566815a8bc3a"
http_archive(
    name = "io_bazel_rules_kotlin",
    urls = ["https://github.com/bazelbuild/rules_kotlin/releases/download/v%s/rules_kotlin_release.tgz" % rules_kotlin_version],
    sha256 = rules_kotlin_sha,
)

load("@io_bazel_rules_kotlin//kotlin:repositories.bzl", "kotlin_repositories")
kotlin_repositories() # if you want the default. Otherwise see custom kotlinc distribution below

load("@io_bazel_rules_kotlin//kotlin:core.bzl", "kt_register_toolchains")
kt_register_toolchains() # to use the default toolchain, otherwise see toolchains below

http_archive(
    name = "io_grpc_grpc_java",
    sha256 = "2afc5d3abb08bf15ed76cb7a99d06bddda16464955b91b1b65b73bd0a1113fa5",
    strip_prefix = "grpc-java-1.57.0",
    urls = ["https://github.com/grpc/grpc-java/archive/v1.57.0.zip"],
)

http_archive(
    name = "com_github_grpc_grpc_kotlin",
    sha256 = "a218306e681318cbbc3b0e72ec9fe1241b2166b735427a51a3c8921c3250216f",
    strip_prefix = "grpc-kotlin-1.4.2",
    urls = ["https://github.com/grpc/grpc-kotlin/archive/refs/tags/v1.4.2.zip"],
)

http_archive(
    name = "rules_jvm_external",
    sha256 = "c21ce8b8c4ccac87c809c317def87644cdc3a9dd650c74f41698d761c95175f3",
    strip_prefix = "rules_jvm_external-1498ac6ccd3ea9cdb84afed65aa257c57abf3e0a",
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/1498ac6ccd3ea9cdb84afed65aa257c57abf3e0a.zip",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@io_grpc_grpc_java//:repositories.bzl", "IO_GRPC_GRPC_JAVA_ARTIFACTS")
load("@io_grpc_grpc_java//:repositories.bzl", "IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS")
load("@io_grpc_grpc_java//:repositories.bzl", "grpc_java_repositories")
load("@com_github_grpc_grpc_kotlin//:repositories.bzl", "IO_GRPC_GRPC_KOTLIN_ARTIFACTS")
load("@com_github_grpc_grpc_kotlin//:repositories.bzl", "IO_GRPC_GRPC_KOTLIN_OVERRIDE_TARGETS")
load("@com_github_grpc_grpc_kotlin//:repositories.bzl", "grpc_kt_repositories")

grpc_java_repositories()
grpc_kt_repositories()

# Protobuf now requires C++14 or higher, which requires Bazel configuration
# outside the WORKSPACE. See .bazelrc in this directory.
load("@com_google_protobuf//:protobuf_deps.bzl", "PROTOBUF_MAVEN_ARTIFACTS")
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

local_repository(
    name = "kdash",
    path = "/Users/williamhester/IdeaProjects/iRacingOverlay/src",
)

maven_install(
    artifacts = [
        "com.google.guava:guava:31.1-jre",
        "com.google.flogger:flogger:0.7.4",
        "com.google.flogger:flogger-system-backend:0.7.4",
        "com.google.protobuf:protobuf-kotlin:3.17.0",
        "com.google.protobuf:protobuf-java-util:3.20.1",
        "com.squareup.okhttp3:okhttp:4.10.0",
        "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10",
        "io.grpc:grpc-api:1.57.0",
        "io.grpc:grpc-all:1.57.0",
        "io.grpc:grpc-netty-shaded:1.57.0",
        "io.grpc:grpc-protobuf:1.57.0",
        "io.grpc:grpc-stub:1.57.0",
        "io.javalin:javalin:jar:4.6.0",
        "org.mindrot:jbcrypt:0.4",
        "org.slf4j:slf4j-simple:1.8.0-beta4",
        "mysql:mysql-connector-java:8.0.29",

        # For testing
        "com.google.truth:truth:1.1.3",
        "junit:junit:4.13.2",

        # For KDash API
        "net.java.dev.jna:jna:5.10.0",
        "net.java.dev.jna:jna-platform:5.10.0",

        "com.google.api.grpc:grpc-google-cloud-pubsub-v1:0.1.24",
        "com.google.api.grpc:proto-google-cloud-pubsub-v1:0.1.24",
    ] + IO_GRPC_GRPC_JAVA_ARTIFACTS + IO_GRPC_GRPC_KOTLIN_ARTIFACTS + PROTOBUF_MAVEN_ARTIFACTS,
    generate_compat_repositories = True,
    override_targets = IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS | IO_GRPC_GRPC_KOTLIN_OVERRIDE_TARGETS,
    repositories = [
        "https://repo.maven.apache.org/maven2/",
    ],
)

load("@maven//:compat.bzl", "compat_repositories")

compat_repositories()
